apps/content/urls.py
from django.conf.urls.defaults import patterns,  url

from . import views

 
urlpatterns = patterns('',
     url(r'^$', views.list_view),
     url(r'^tag/(?P<tag_slug>[-\w]+)$', views.list_view),
     url(r'^(?P<slug>[-\w]+)$', views.single_entry),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mirto.views.home', name='home'),
    # url(r'^mirto/', include('mirto.foo.urls')),

     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^grappelli/', include('grappelli.urls')),
     url(r'', include('apps.content.urls')),
)


#THIS IS FOR DEVELOPMENT STATIC MEDIA
# -----------------------------------
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': True
            }
        ),
    )
# -----------------------------------

apps/content/models.py
from django.db import models
from django.template import Context
from django.template.loader import get_template
from sorl.thumbnail import ImageField


class Tag(models.Model):
    tag = models.CharField(
        max_length=100
        )
    
    slug = models.SlugField(
        max_length=100
        )

    show_in_tag_list = models.BooleanField(
        default = True
    )

    order = models.IntegerField(default=0)

    @staticmethod
    def render_list(context):
        
       
        context['tag_list']  = Tag.objects.filter(show_in_tag_list = True)
      
        
        t = get_template('content/tag.list.html')
        
        return t.render(context)

    def __unicode__(self):
        return unicode(self.tag)

    class Meta:
        ordering = ['order',]

class Image(models.Model):
    image = ImageField(
        upload_to='images'
        )
    caption = models.TextField(
        max_length=1000, 
        blank=True
        )
    entry = models.ForeignKey(
        'Entry'
        )
    
    order = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['order',]

# Create your models here.
class Entry(models.Model):
    title = models.CharField(
        max_length=255
        )
    
    slug = models.SlugField(
        max_length=255
        )

    order = models.IntegerField(default=0)
    
    preview_image = ImageField(
        upload_to='images',
        blank=True,
        null=True
        )
    
    date = models.DateField(
        blank=True,
        null=True
    )
    
    is_published = models.BooleanField()
    
    include_on_front_page = models.BooleanField()
    
    tags = models.ManyToManyField(Tag, blank=True)
    
    main_content     = models.TextField(
        blank=True
        )
    
    seo_keywords     = models.CharField(
        max_length=255,
        help_text='A short list of words for Google that describe this entry, seperated by commas'
        )
    
    seo_description  = models.TextField(
        max_length=1000,
        help_text='A short description for Google'
        )
    
    def tag_list(self):
        return ", ".join(self.tags.values_list('tag', flat=True))

    def get_absolute_url(self):
        return '/' + self.slug
    
    def __unicode__(self):
        return unicode(self.title)
    
    class Meta:
        verbose_name = 'Entry'
        verbose_name_plural = 'Entries'
        ordering = ['order',]

apps/layout/models.py
from django.db import models
from django.template.loader import get_template
from django.template import Context
from ..content import models as content_models

class Menu(models.Model):
    STYLES = (('black', 'Black'),
              ('orange', 'Orange'),)
    
    title = models.CharField(max_length=40)
    style = models.CharField(max_length=40, choices=STYLES)
    show_title = models.BooleanField(default=True, help_text="Show the title above the menu?")
    
    def item_count(self):
        return self.menuitem_set.count()
    
    def render(self, context):
        c = Context({'menu' : self})
        return get_template('layout/menu.html').render(c)
    
    def __unicode__(self):
        return unicode(self.title)
    
class MenuItem(models.Model):
   
    LINK_TYPE_CHOICES = (
        ('custom', 'Custom link'),
        ('tag', 'Link to tag'),
        ('entry', 'Link to entry'),
    )
   
    TARGET_CHOICES = (
        ('_blank', 'Open in a new window'),
        ('_self', 'Open in the same window'),
    )
    
    order   = models.IntegerField()
    text    = models.CharField(max_length=1000)
    target  = models.CharField(max_length=50, choices=TARGET_CHOICES, default='_self')
    link_type = models.CharField(choices=LINK_TYPE_CHOICES, max_length=50, default='custom')
    custom_link =models.URLField(blank=True)
    link_to_entry = models.ForeignKey(content_models.Entry, blank=True, null=True)
    link_to_tag = models.ForeignKey(content_models.Tag, blank=True, null=True)

    menu = models.ForeignKey(Menu)
    
    def links_to(self):
        if self.link_type == 'none':
            return ''
        if self.link_type == 'custom':
            return self.custom_link
        if self.link_type == 'entry':
            return self.link_to_entry.get_absolute_url()
        
        
    
        
    def __unicode__(self):
        return self.text
    
    class Meta:
        ordering = ['order']


class BlockArea(models.Model):
    key = models.CharField(max_length=100)

    def render(self, context):
        html = ''
        for block in self.block_set.all():
            html += '<div class="block">' + block.render(context) + '</div>'
        
        return html
    
class Block(models.Model):
    
    TYPES = (('html', 'HTML Block'),
             ('tag_list', 'Tag List'),
             ('menu', 'Menu Block'))
    
    block_area = models.ForeignKey(BlockArea)
    
    block_type = models.CharField(choices=TYPES, max_length=30)
    
    html = models.TextField(blank=True, null=True)
    
    menu = models.ForeignKey(Menu,blank=True, null=True)
    
    order = models.IntegerField()
    
    def render(self, context):
        if self.block_type == 'html':
            return self.html
        elif self.block_type == 'tag_list':
            context.tag_list = ""
            return content_models.Tag.render_list(context=context)
        elif self.block_type == 'menu':
            return self.menu.render(context=context)
       
    def __unicode__(self):
        if self.block_type == 'html':
            return 'HTML'
        elif self.block_type == 'tag_list':
            return 'Tag List'
        elif self.block_type == 'menu':
            return 'Menu - ' + self.menu.title 
    
    class Meta:
        ordering = ['order',]

apps/content/views.py
# Create your views here.

from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from . import models

def single_entry(request, slug):
    
    entry = get_object_or_404(models.Entry, slug=slug)
    
    tag_slug = request.GET.get('tag', None)

    return render_to_response(
        'content/template.single_entry.html',
        {'entry': entry,
         'tag_slug' : tag_slug},
        context_instance=RequestContext(request)
        )


def list_view(request, tag_slug=None):
    
    if tag_slug is not None:
        #single tag
        tag = get_object_or_404(models.Tag, slug=tag_slug)
        entries = tag.entry_set.filter(is_published=True)
        page_title = tag.tag
    else:
        #home page
        entries = models.Entry.objects.filter(is_published=True, include_on_front_page=True)
        page_title = ''
    
  
    return render_to_response(
        'content/template.list.html',
        {
         'entries' : entries,
         'page_title' : page_title,
         'tag_slug' : tag_slug
         },
        context_instance=RequestContext(request)
        )

apps/content/templates/content/entry.preview.html
{% load thumbnail %}

<div class="entryPreview">
	{% if entry.preview_image %}
		{% thumbnail entry.preview_image "300" as im %}
			<a href="{{entry.get_absolute_url}}?tag={{tag_slug}}">
		    	<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
		    </a>
		{% endthumbnail %}
	{% endif %}
	<h3 class="entryPreviewTitle">
		<a href="{{entry.get_absolute_url}}?tag={{tag_slug}}">{{entry.title}}</a>
	</h3>
</div>

apps/content/templates/content/tag.list.html
<ul id="tagList">
	{% for tag in tag_list %}
	<li><a href="/tag/{{tag.slug}}">{{tag.tag}}</a>

	{% if tag_slug and tag.slug == tag_slug %}
		
		{% for tag_entry in tag.entry_set.all %}
			 <a class="{% if tag_entry == entry %}currentTagEntry{% endif%}"
				href="{{tag_entry.get_absolute_url}}?tag={{tag_slug}}"> - {{ tag_entry.title }}</a> 
		{% endfor %}
		<br>
	{% endif %}

	</li>
	{% endfor %}
</ul>

apps/content/templates/content/template.list.html
{% extends "base/template.base.html" %}


{% block javascript %}

<script type="text/javascript" src="{{ STATIC_URL}}base/js/jquery.masonry.min.js"></script>
<script type="text/javascript">
	
	$(function() {
		

		var sizeElements = function() {
    		$('#holder').width($(window).width()).height($(window).height());
    		$('#contentHolder').width($(window).width() - 305);
    		$('.entries').masonry({
				  itemSelector: '.entryPreview',
				  isFitWidth: true
			});
    	};

    	$(window).resize(sizeElements);
    	sizeElements();

	});
	
</script>

{% endblock %}

{% block content %}
<div id="contentHolder">
		<div class="entries">
			{% for entry in entries %}
				{% include 'content/entry.preview.html' %}
			{% endfor %}
		</div>
		<div style="clear:both;"></div>
</div>
{% endblock %}

apps/content/templates/content/template.single_entry.html
{% extends "base/template.base.html" %}
{% load thumbnail %}

{%block meta_title %}{{entry.title}} - Martina Vanda {%endblock%}
{% block meta_keywords %}{{entry.seo_keywords}}{% endblock %}
{% block meta_description %}{{entry.seo_description}}{% endblock %}

{% block body_class%}entry{% endblock%}


{% block javascript %}
	<script type="text/javascript">

        $(function() {

        	var totalEntryWidth = 0;
        	$('.contentBox').each(function(index, entry) {
        		totalEntryWidth += $(this).width() + 40;
        	});

        	$('#content').width(totalEntryWidth)

        	var sizeElements = function() {
        		$('#holder').width($(window).width()).height($(window).height());
        		$('#contentHolder').width($(window).width() - 305);

        	};

        	$(window).resize(sizeElements);
        	sizeElements();

        	var scrollInterval = false;
        	$(document).mouseup(function() {
        		try {
        			clearInterval(scrollInterval);
        		} catch(e) {}
        	});

        	$('#scrollPrev').mousedown(function(){
        		scrollInterval = setInterval(function() {
        			$('#contentHolder').scrollLeft($('#contentHolder').scrollLeft()-10);
        		}, 20);
        	});


        	$('#scrollNext').mousedown(function(){
        		scrollInterval = setInterval(function() {
        			$('#contentHolder').scrollLeft($('#contentHolder').scrollLeft()+10);
        		}, 20);
        	});
        	
        	$('#entryLikeButton').attr('data-href',window.location.href.substring(0,window.location.href.indexOf('?')));
        	
        	(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

        });

     </script>
{% endblock %}

{% block pageTitle%} {{entry.title}} {% endblock%}

{% block content %}
	
<div id="scrollControls">
	<div id="scrollPrev"></div>
	<div id="scrollNext"></div>
</div>

<div id="contentHolder">
	<div id="content">
		<div class="entries">


			{% for entry_image in entry.image_set.all %}
				{% thumbnail entry_image.image "x500" upscale=False as im %}
				<div class="contentBox" style="width:{{im.width }}px">
		
				    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
					<h2 class="entryFullImageCaption">{{entry_image.caption|linebreaksbr}}</h2>
				</div>
				{% endthumbnail %}
		
			{% endfor %}

		</div>
					
		<div style="clear:both;"></div>
	</div>		
</div>



<div id="entryDescriptionBox" >
		{% autoescape off %}
			{{entry.main_content}}
		{% endautoescape %}
</div>


<div id="entryLikeButton" class="fb-like" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>

{% endblock %}

apps/layout/templates/layout/menu.html
<div class="menu {{menu.style}}">
	{% if menu.show_title %}
		<h3 class="menuTitle">{{menu.title}}</h3>
	{% endif %}
	<ul>
		{%for menu_item in menu.menuitem_set.all%}
			<li><a href="{{menu_item.links_to}}" target="{{menu_item.target}}">{{menu_item.text}}</a></li>
		{% endfor %}
	</ul>
</div>

templates/base/template.base.html
{% load block_areas %}
<!DOCTYPE html>
<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="author" content="Martina Vanda" />
		<meta name="description" content="{% block meta_description %}Martina Vanda{% endblock %}" />
		<meta name="keywords" content="{% block meta_keywords %}Martina Vanda{% endblock %}" />
		<title>{%block meta_title %} Martina Vanda {% endblock %} </title>
		
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL}}base/css/base.css" />
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL}}content/css/content.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        
		{% block javascript %}
		{% endblock %}
	<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-4643076-1']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
	
	</script>

	</head>
	
	<body class="{% block body_class%}{% endblock%}">
			
		<div id="holder">
			<div id="sidebar">

				{% autoescape off %}
					{% render_block_area 'sidebar' %}
				{% endautoescape %}
			</div>	
			<h2 id="pageTitle">{% block pageTitle %}{% endblock %}</h2>
			
			{% block content %}
			{% endblock %}
		</div>	
		<div id="fb-root"></div>
	</body>
</html>